-- Source DWH: Netezza-style sample DDL
CREATE TABLE CORE.ACCOUNT (
    ACCOUNT_ID BIGINT NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    BRANCH_ID INTEGER NOT NULL,
    ACCOUNT_TYPE VARCHAR(20),
    STATUS_CD CHAR(1),
    OPEN_DATE DATE,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ACCOUNT_ID)
)
DISTRIBUTE ON (ACCOUNT_ID);
