-- Source DWH: Netezza-style sample DDL for branch master
CREATE TABLE CORE.BRANCH (
    BRANCH_ID INTEGER NOT NULL,
    BRANCH_NAME VARCHAR(60) NOT NULL,
    REGION_CD VARCHAR(10),
    OPEN_DATE DATE,
    STATUS_CD CHAR(1),
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (BRANCH_ID)
)
DISTRIBUTE ON (BRANCH_ID);
