-- Source DWH: Netezza-style sample DDL
CREATE TABLE CORE.CUSTOMER (
    CUSTOMER_ID INTEGER NOT NULL,
    CUSTOMER_SEGMENT VARCHAR(20),
    OPEN_DATE DATE,
    RISK_SCORE NUMERIC(5,2),
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID)
)
DISTRIBUTE ON (CUSTOMER_ID);
