-- Source DWH: Netezza-style sample DDL
CREATE TABLE CORE.TRANSACTION (
    TRANSACTION_ID BIGINT NOT NULL,
    ACCOUNT_ID BIGINT NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    AMOUNT NUMERIC(18,2) NOT NULL,
    CHANNEL_CD VARCHAR(10),
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (TRANSACTION_ID)
)
DISTRIBUTE ON (ACCOUNT_ID);
