-- Source DWH: Netezza-style sample view
CREATE VIEW MART.VW_BRANCH_BALANCE AS
SELECT
    a.BRANCH_ID,
    t.TRANSACTION_DATE,
    SUM(t.AMOUNT) AS DAILY_AMOUNT,
    COUNT(*) AS TRANSACTION_COUNT
FROM CORE.ACCOUNT a
JOIN CORE.TRANSACTION t
    ON a.ACCOUNT_ID = t.ACCOUNT_ID
GROUP BY a.BRANCH_ID, t.TRANSACTION_DATE;
